spring:
  profiles:
    active: bbc-kata-specification
  i18n:
    basename: i18n
    encoding: UTF-8
    cache-seconds: -1

  main:
    web-environment: false

logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR

application-i18n:
  null-mapping-table-error: 'The decimal to numerals table cannot be null. The application is not in an operational state.'
  invalid-numeral-key-error: 'The numeral key passed into the numerals table should always exist.'
  null-numeral-key-error: 'The numeral key passed into the numerals table cannot be null.'
  number-too-small-validation-msg: 'Please enter a valid decimal number - the input value must be between 1 and 3999 (inclusive)'

---

spring:
  profiles: bbc-kata-specification

input-limits:
  from-integer:
    minimum-input-integer: 1
    maximum-input-integer: 3999

numeral-representation:
  numeral-table:
    decimal-to-numeral-map:
      1: 'I'
      4: 'IV'
      5: 'V'
      9: 'IX'
      10: 'X'
      40: 'XL'
      50: 'L'
      90: 'XC'
      100: 'C'
      400: 'CD'
      500: 'D'
      900: 'CM'
      1000: 'M'
